services:
  drivers-assignment-management-service:
    build: .
    container_name: drivers-assignment-management-service
    environment:
      - EUREKA_SERVER_HOST=discovery-server
      - EUREKA_SERVER_PORT=8761
      - GATEWAY_PORT=8080
      - DB_PORT=5432
      - DB_HOST_ROUTE=postgres-main
      - DB_NAME_ROUTE=gtu_main_db
      - DB_USER=user
      - DB_PASSWORD=password
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - SERVER_PORT=0
      - SWAGGER_SERVER_URL=${SWAGGER_SERVER_URL}
    networks:
      - shared_network
networks:
  shared_network:
    external: true

