spring:
  application:
    name: drivers_assignment_management_service

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:postgresql://postgres-main:5432/gtu_main_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8081}

secondary:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:postgresql://postgres-users:5432/gtu_users_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

eureka:
  instance:
    preferIpAddress: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false
